name: movie_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_launcher_icons: ^0.13.1

  google_fonts: ^6.2.1

  flutter_carousel_widget: ^3.1.0
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.3
  dio: ^5.7.0

  share_plus: ^10.1.1
  equatable: ^2.0.5

flutter_icons:
  image_path: "assets/icon/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "ic_launcher"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon-android.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/empty.json
    - assets/splash.json
    - assets/error_state.json
